### ISSUE TITLE
Use an html parser instead of pupeteer

### ISSUE THREAD

**Issue by sazid** [imSaharukh/AIUB-NOTICE-BOT#1]
Took a glance through your code, I haven't developed much with nodejs but from what I can tell pupeteer is a whole browser instance running in headless mode. This seems like an overkill for just a simple purpose of parsing HTML. I'll suggest you to take a look at [https://github.com/cheeriojs/cheerio](https://github.com/cheeriojs/cheerio) which should be fairly easy to integrate and does not need any headless browser instance to be running. I was successful using this technique to figure out any new notice posted in my android app.

**Comment by imSaharukh** [comment]
I'm using pupeteer because I'm planning to add portal notification also. I'm new in NodeJS this is my 1st project :p using node

**Comment by sazid** [comment]
I see, good luck!
Parsing portal notifications is a bit tricky but it shouldn't be that hard. You can take a look at [this file](https://github.com/sazid/aiub-app/blob/master/app/src/main/java/com/mohammedsazid/android/aiub/workers/PortalNotificationWorker.kt) if you need a head start.

**Comment by imSaharukh** [comment]
Thanks
